

version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nyc_postgres
    environment:
      POSTGRES_USER: nyc_user
      POSTGRES_PASSWORD: nyc_pass
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: